# Generated by Django 4.2.15 on 2025-06-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AutoLabelingConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("model_name", models.CharField(max_length=100)),
                ("model_attrs", models.JSONField(default=dict)),
                ("template", models.TextField(default="")),
                ("label_mapping", models.JSONField(blank=True, default=dict)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("Category", "category"),
                            ("Span", "span"),
                            ("Text", "text"),
                            ("Relation", "relation"),
                        ],
                        max_length=100,
                    ),
                ),
                ("default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
