# Generated by Django 4.2.15 on 2025-06-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_annotation_open",
            field=models.BooleanField(
                default=True, help_text="If False, users cannot edit their perspectives or annotate."
            ),
        ),
    ]
