# Generated by Django 4.2.15 on 2025-06-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_add_perspective_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perspectivefield",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="projectperspective",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="userperspectiveanswer",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
