# Generated by Django 4.2.15 on 2025-06-28 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("examples", "0006_example_is_resolved"),
        ("labels", "0002_alter_category_example_datasetversion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="example",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="categories", to="examples.example"
            ),
        ),
        migrations.DeleteModel(
            name="CategoryVersion",
        ),
    ]
