# Generated by Django 4.2.15 on 2025-07-06 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("label_types", "0002_initial"),
        ("labels", "0003_alter_category_example_delete_categoryversion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasetversion",
            name="label",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="label_types.categorytype"
            ),
        ),
        migrations.AlterModelTable(
            name="datasetversion",
            table="labels_datasetversion",
        ),
    ]
