# Generated by Django 4.2.15 on 2025-06-07 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("examples", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="example",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="examples", to="projects.project"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="example",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="examples.example"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="assignee",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="assignment",
            name="example",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="assignments", to="examples.example"
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="assignments", to="projects.project"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examplestate",
            unique_together={("example", "confirmed_by")},
        ),
        migrations.AlterUniqueTogether(
            name="assignment",
            unique_together={("example", "assignee")},
        ),
    ]
