# Generated by Django 4.2.15 on 2025-06-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examples", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="example",
            name="has_discrepancy",
            field=models.BooleanField(default=False, help_text="Admin flag for annotation discrepancy."),
        ),
    ]
