# Generated by Django 4.2.15 on 2025-06-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examples", "0003_example_has_discrepancy"),
    ]

    operations = [
        migrations.AddField(
            model_name="example",
            name="annotation_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="example",
            name="annotation_start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="example",
            name="is_finished",
            field=models.BooleanField(default=False),
        ),
    ]
