# Generated by Django 4.2.15 on 2025-06-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examples", "0004_example_annotation_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="example",
            name="has_discrepancies_automatica",
            field=models.BooleanField(default=False, help_text="Automatic flag for annotation discrepancy."),
        ),
    ]
