# Generated by Django 4.2.15 on 2025-06-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examples", "0005_example_has_discrepancies_automatica"),
    ]

    operations = [
        migrations.AddField(
            model_name="example",
            name="is_resolved",
            field=models.BooleanField(default=False),
        ),
    ]
