# Generated by Django X.X on 202X-XX-XX XX:XX
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),  # Ajuste conforme seu app de projetos
    ]

    operations = [
        migrations.CreateModel(
            name='Perspective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerspectiveProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perspective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspective.perspective')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'db_table': 'perspective_perspective_projects',
                'unique_together': {('perspective', 'project')},
            },
        ),
        migrations.AddField(
            model_name='perspective',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='perspective', through='perspective.PerspectiveProject', to='projects.project'),
        ),
    ]