# Generated by Django 4.2.15 on 2025-04-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_project_allow_member_to_create_label_type_and_more"),
        ("perspective", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perspective",
            name="projects",
            field=models.ManyToManyField(
                blank=True,
                db_table="perspective_perspective_projects",
                related_name="perspective",
                to="projects.project",
            ),
        ),
        migrations.DeleteModel(
            name="PerspectiveProject",
        ),
    ]
