# Generated by Django 4.2.15 on 2025-04-02 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("perspective", "0002_alter_perspective_projects_delete_perspectiveproject"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="perspective",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="perspective",
            name="projects",
        ),
    ]
