# Generated by Django 4.2.15 on 2025-06-07 22:15

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("label_types", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DummyLabelType",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("label_types.categorytype",),
        ),
    ]
