# Generated by Django 4.2.15 on 2025-03-31 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_project_allow_member_to_create_label_type_and_more"),
        ("perspectives", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userperspectiveanswer",
            options={
                "verbose_name": "Resposta de Perspetiva do Utilizador",
                "verbose_name_plural": "Respostas de Perspetiva dos Utilizadores",
            },
        ),
        migrations.RemoveField(
            model_name="projectperspective",
            name="fields",
        ),
        migrations.AlterField(
            model_name="projectperspective",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="project_perspective", to="projects.project"
            ),
        ),
        migrations.CreateModel(
            name="Perspective",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("fields", models.ManyToManyField(related_name="perspectives", to="perspectives.perspectivefield")),
            ],
        ),
        migrations.AddField(
            model_name="projectperspective",
            name="perspective",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="perspectives.perspective",
            ),
        ),
    ]
