# Generated by Django 4.2.15 on 2025-06-07 22:15

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("labels", "0001_initial"),
        ("examples", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportedBoundingBox",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("labels.boundingbox",),
        ),
        migrations.CreateModel(
            name="ExportedCategory",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("labels.category",),
        ),
        migrations.CreateModel(
            name="ExportedComment",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("examples.comment",),
        ),
        migrations.CreateModel(
            name="ExportedExample",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("examples.example",),
        ),
        migrations.CreateModel(
            name="ExportedRelation",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("labels.relation",),
        ),
        migrations.CreateModel(
            name="ExportedSegmentation",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("labels.segmentation",),
        ),
        migrations.CreateModel(
            name="ExportedSpan",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("labels.span",),
        ),
        migrations.CreateModel(
            name="ExportedText",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("labels.textlabel",),
        ),
    ]
